"""
@author: Dylan Pare
@name: make_mask.py
@date: 03/14/2023
@description: Create a mask to remove artifact pixels caused by e.g. edge pixels.
"""

# Import needed packages
import numpy as np
from astropy.io import fits
import os
import glob

# Get set of residstd files generated by scousepy
cwd = os.getcwd()
fits_dir = cwd + '../HC3N_TP_7m_12m_feather/stage_4/'
rms_files = glob.glob(fits_dir + '*rms*refit.fits')
rms_names = [os.path.basename(x) for x in glob.glob(fits_dir+'/*rms*refit.fits')]
mask_prefix = ['v0','v1','v2']

# Read in residstd file and create a mask file based on residstd threshold
for file in range(len(rms_files)):

	print(rms_names[file])
	rms_file = rms_files[file]
	image    = fits.open(rms_file)
	data     = image[0].data
	header   = image[0].header
	mean     = np.mean(data[~np.isnan(data)])
	thresh_h = 1.5*mean
	thresh_l = mean/1.5

	mask = np.zeros(data.shape)
	for x in range(len(data)):
		for y in range(len(data[0])):
			if (data[x][y] >= thresh_h) or (data[x][y] <= thresh_l):
				mask[x][y] = 1.0

	fits.writeto(mask_prefix[file]+'_mask.fits',data=mask,header=header,overwrite=True)

