"""
@author: Dylan Pare
@name: make_mask.py
@date: 03/14/2023
@description: Create a mask to remove artifact pixels caused by e.g. edge pixels.
"""

# Import needed packages
import numpy as np
from astropy.io import fits
import os
import glob

# Get set of residstd files generated by scousepy
path = os.getcwd()
parent = os.path.dirname(path)
print(parent)
fits_dir  = parent + '/HC3N_TP_7m_12m_feather/stage_4/'
rms_files = glob.glob(fits_dir + '*rms*refit.fits')
rms_names = [os.path.basename(x) for x in glob.glob(fits_dir+'*rms*refit.fits')]
pb_file   = parent + '/SgrB2_PrimaryBeam_new.fits'
pb_im     = fits.open(pb_file)
pb_data   = pb_im[0].data
pb_thresh = 0.5

mask_prefix = ['v0','v1','v2']

# Read in PB file and create a mask file based on PB response threshold
for file in range(len(rms_files)):

	print(rms_names[file])
	rms_file   = rms_files[file]
	rms_image  = fits.open(rms_file)
	rms_data   = rms_image[0].data
	rms_header = rms_image[0].header

	mask = np.zeros(rms_data.shape)
	for x in range(len(rms_data)):
		for y in range(len(rms_data[0])):
			if (pb_data[x][y] <= pb_thresh) or (np.isnan(pb_data[x][y]) == True):
				mask[x][y] = 1.0

	fits.writeto(mask_prefix[file]+'_mask.fits',data=mask,header=rms_header,overwrite=True)

